os:
  - linux
  - osx

env:
  - TARGET=spec
  - TARGET=spec2

apt:
  packages:
    - crystal-lang

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update              ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install crystal-lang; fi

script:
  - crystal deps
  - crystal spec -D $TARGET
